vscode:
  extensions:
    - ritwickdey.liveserver@5.6.1:5Mhl1RgVVDcIym163x8r+w==
    - ms-vscode.js-debug@1.52.2:8PDBHJwYVbbTyHsjB5DJSQ==

ports:
  - port: 8080
    onOpen: ignore

tasks:
  - command: gp preview $(gp url 8080)tutorial5/index.html
